In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
movie_df_raw = pd.read_csv("/content/drive/MyDrive/Data Mining/week 02 - 12-02-2025/03 Recommendation System 2/ratings.csv")
movie_names = pd.read_csv("/content/drive/MyDrive/Data Mining/week 02 - 12-02-2025/03 Recommendation System 2/movies.csv")

In [ ]:
movie_df_raw

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [ ]:
movie_names

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [ ]:
movie_df = pd.DataFrame(columns=movie_df_raw['movieId'].unique(), index=movie_df_raw['userId'].unique())
movie_df

,1,3,6,47,50,70,101,110,151,157,...,147662,148166,149011,152372,158721,160341,160527,160836,163937,163981
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
for i in range(movie_df_raw.shape[0]):
  row = movie_df_raw.iloc[i]
  user = row['userId']
  movie = row['movieId']
  rating = row['rating']

  movie_df.loc[user, movie] = rating

Streaming output truncated to the last 5000 lines.
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '4.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating
<ipython-input-18-5f4a6589e852>:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  movie_df.loc[user, movie] = rating

In [ ]:
movie_df = movie_df.fillna(0)
movie_df

<ipython-input-6-7b5d9cfeccf2>:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  movie_df = movie_df.fillna(0)

,1,3,6,47,50,70,101,110,151,157,...,147662,148166,149011,152372,158721,160341,160527,160836,163937,163981
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
607,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
608,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
609,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
610,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
user_ratings = {48780:4.8, 74458:4.8, 87222:4.5, 88069:4.0, 99813:5, 104879:5, 115149:4.8, 184641:4.0, 176371:4, 185585:3.5, 102125:2.5}
user_df = pd.DataFrame(user_ratings, columns=movie_df.columns, index=[611])
user_df = user_df.fillna(0)
user_df

<ipython-input-7-34fd10b9f831>:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  user_df = user_df.fillna(0)

,1,3,6,47,50,70,101,110,151,157,...,147662,148166,149011,152372,158721,160341,160527,160836,163937,163981
611,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
movie_df = pd.concat([movie_df, user_df])
movie_df

,1,3,6,47,50,70,101,110,151,157,...,147662,148166,149011,152372,158721,160341,160527,160836,163937,163981
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
607,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
608,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
609,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
610,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
611,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
from scipy.spatial.distance import euclidean

def euclidean_similarity(user1, user2):
  common_ratings = (user1 != 0 ) & (user2 != 0)
  if np.sum(common_ratings) == 0:
    return 0
  distance = euclidean(user1[common_ratings], user2[common_ratings])
  similarity = 1/(1+distance)
  return similarity

In [ ]:
target_user = 611

user_similarities = {}

for user in movie_df.index:
  if user != target_user:
    similarity = euclidean_similarity(movie_df.loc[target_user], movie_df.loc[user])
    user_similarities[user] = similarity

Enter your own movie ratings here.

In [ ]:
user_similarities

{1: 0,
 2: 0,
 3: 0,
 4: 0,
 5: 0,
 6: 0,
 7: 0,
 8: 0,
 9: 0,
 10: 0,
 11: 0,
 12: 0,
 13: 0,
 14: 0,
 15: 0,
 16: 0,
 17: 0,
 18: 0,
 19: 0,
 20: 0,
 21: 0,
 22: 0,
 23: 0,
 24: 0,
 25: 0,
 26: 0,
 27: 0,
 28: 0,
 29: 0,
 30: 0,
 31: 0,
 32: 0,
 33: 0,
 34: 0,
 35: 0,
 36: 0,
 37: 0,
 38: 0,
 39: 0,
 40: 0,
 41: 0,
 42: 0,
 43: 0,
 44: 0,
 45: 0,
 46: 0,
 47: 0,
 48: 0,
 49: 0,
 50: 0,
 51: 0,
 52: 0,
 53: 0,
 54: 0,
 55: 0,
 56: 0,
 57: 0,
 58: 0,
 59: 0,
 60: 0,
 61: 0,
 62: 0,
 63: 0,
 64: 0,
 65: 0,
 66: 0,
 67: 0,
 68: 0,
 69: 0,
 70: 0,
 71: 0,
 72: 0,
 73: 0,
 74: 0,
 75: 0,
 76: 0,
 77: 0,
 78: 0,
 79: 0,
 80: 0,
 81: 0,
 82: 0,
 83: 0,
 84: 0,
 85: 0,
 86: 0,
 87: 0,
 88: 0,
 89: 0,
 90: 0,
 91: 0,
 92: 0,
 93: 0,
 94: 0,
 95: 0,
 96: 0,
 97: 0,
 98: 0,
 99: 0,
 100: 0,
 101: 0,
 102: 0,
 103: 0,
 104: 0,
 105: 0,
 106: 0,
 107: 0,
 108: 0,
 109: 0,
 110: 0,
 111: 0,
 112: 0,
 113: 0,
 114: 0,
 115: 0,
 116: 0,
 117: 0,
 118: 0,
 119: 0,
 120: 0,
 121: 0,
 122: 0,
 123: 0,
 124: 0,
 125: 0,
 126: 0,
 127: 0,
 128: 0,
 129: 0,
 130: 0,
 131: 0,
 132: 0,
 133: 0,
 134: 0,
 135: 0,
 136: 0,
 137: 0,
 138: 0,
 139: 0,
 140: 0,
 141: 0,
 142: 0,
 143: 0,
 144: 0,
 145: 0,
 146: 0,
 147: 0,
 148: 0,
 149: 0,
 150: 0,
 151: 0,
 152: 0,
 153: 0,
 154: 0,
 155: 0,
 156: 0,
 157: 0,
 158: 0,
 159: 0,
 160: 0,
 161: 0,
 162: 0,
 163: 0,
 164: 0,
 165: 0,
 166: 0,
 167: 0,
 168: 0,
 169: 0,
 170: 0,
 171: 0,
 172: 0,
 173: 0,
 174: 0,
 175: 0,
 176: 0,
 177: 0,
 178: 0,
 179: 0,
 180: 0,
 181: 0,
 182: 0,
 183: 0,
 184: 0,
 185: 0,
 186: 0,
 187: 0,
 188: 0,
 189: 0,
 190: 0,
 191: 0,
 192: 0,
 193: 0,
 194: 0,
 195: 0,
 196: 0,
 197: 0,
 198: 0,
 199: 0,
 200: 0,
 201: 0,
 202: 0,
 203: 0,
 204: 0,
 205: 0,
 206: 0,
 207: 0,
 208: 0,
 209: 0,
 210: 0,
 211: 0,
 212: 0,
 213: 0,
 214: 0,
 215: 0,
 216: 0,
 217: 0,
 218: 0,
 219: 0,
 220: 0,
 221: 0,
 222: 0,
 223: 0,
 224: 0,
 225: 0,
 226: 0,
 227: 0,
 228: 0,
 229: 0,
 230: 0,
 231: 0,
 232: 0,
 233: 0,
 234: 0,
 235: 0,
 236: 0,
 237: 0,
 238: 0,
 239: 0,
 240: 0,
 241: 0,
 242: 0,
 243: 0,
 244: 0,
 245: 0,
 246: 0,
 247: 0,
 248: 0,
 249: 0,
 250: 0,
 251: 0,
 252: 0,
 253: 0,
 254: 0,
 255: 0,
 256: 0,
 257: 0,
 258: 0,
 259: 0,
 260: 0,
 261: 0,
 262: 0,
 263: 0,
 264: 0,
 265: 0,
 266: 0,
 267: 0,
 268: 0,
 269: 0,
 270: 0,
 271: 0,
 272: 0,
 273: 0,
 274: 0,
 275: 0,
 276: 0,
 277: 0,
 278: 0,
 279: 0,
 280: 0,
 281: 0,
 282: 0,
 283: 0,
 284: 0,
 285: 0,
 286: 0,
 287: 0,
 288: 0,
 289: 0,
 290: 0,
 291: 0,
 292: 0,
 293: 0,
 294: 0,
 295: 0,
 296: 0,
 297: 0,
 298: 0,
 299: 0,
 300: 0,
 301: 0,
 302: 0,
 303: 0,
 304: 0,
 305: 0,
 306: 0,
 307: 0,
 308: 0,
 309: 0,
 310: 0,
 311: 0,
 312: 0,
 313: 0,
 314: 0,
 315: 0,
 316: 0,
 317: 0,
 318: 0,
 319: 0,
 320: 0,
 321: 0,
 322: 0,
 323: 0,
 324: 0,
 325: 0,
 326: 0,
 327: 0,
 328: 0,
 329: 0,
 330: 0,
 331: 0,
 332: 0,
 333: 0,
 334: 0,
 335: 0,
 336: 0,
 337: 0,
 338: 0,
 339: 0,
 340: 0,
 341: 0,
 342: 0,
 343: 0,
 344: 0,
 345: 0,
 346: 0,
 347: 0,
 348: 0,
 349: 0,
 350: 0,
 351: 0,
 352: 0,
 353: 0,
 354: 0,
 355: 0,
 356: 0,
 357: 0,
 358: 0,
 359: 0,
 360: 0,
 361: 0,
 362: 0,
 363: 0,
 364: 0,
 365: 0,
 366: 0,
 367: 0,
 368: 0,
 369: 0,
 370: 0,
 371: 0,
 372: 0,
 373: 0,
 374: 0,
 375: 0,
 376: 0,
 377: 0,
 378: 0,
 379: 0,
 380: 0,
 381: 0,
 382: 0,
 383: 0,
 384: 0,
 385: 0,
 386: 0,
 387: 0,
 388: 0,
 389: 0,
 390: 0,
 391: 0,
 392: 0,
 393: 0,
 394: 0,
 395: 0,
 396: 0,
 397: 0,
 398: 0,
 399: 0,
 400: 0,
 401: 0,
 402: 0,
 403: 0,
 404: 0,
 405: 0,
 406: 0,
 407: 0,
 408: 0,
 409: 0,
 410: 0,
 411: 0,
 412: 0,
 413: 0,
 414: 0,
 415: 0,
 416: 0,
 417: 0,
 418: 0,
 419: 0,
 420: 0,
 421: 0,
 422: 0,
 423: 0,
 424: 0,
 425: 0,
 426: 0,
 427: 0,
 428: 0,
 429: 0,
 430: 0,
 431: 0,
 432: 0,
 433: 0,
 434: 0,
 435: 0,
 436: 0,
 437: 0,
 438: 0,
 439: 0,
 440: 0,
 441: 0,
 442: 0,
 443: 0,
 444: 0,
 445: 0,
 446: 0,
 447: 0,
 448: 0,
 449: 0,
 450: 0,
 451: 0,
 452: 0,
 453: 0,
 454: 0,
 455: 0,
 456: 0,
 457: 0,
 458: 0,
 459: 0,
 460: 0,
 461: 0,
 462: 0,
 463: 0,
 464: 0,
 465: 0,
 466: 0,
 467: 0,
 468: 0,
 469: 0,
 470: 0,
 471: 0,
 472: 0,
 473: 0,
 474: 0,
 475: 0,
 476: 0,
 477: 0,
 478: 0,
 479: 0,
 480: 0,
 481: 0,
 482: 0,
 483: 0,
 484: 0,
 485: 0,
 486: 0,
 487: 0,
 488: 0,
 489: 0,
 490: 0,
 491: 0,
 492: 0,
 493: 0,
 494: 0,
 495: 0,
 496: 0,
 497: 0,
 498: 0,
 499: 0,
 500: 0,
 501: 0,
 502: 0,
 503: 0,
 504: 0,
 505: 0,
 506: 0,
 507: 0,
 508: 0,
 509: 0,
 510: 0,
 511: 0,
 512: 0,
 513: 0,
 514: 0,
 515: 0,
 516: 0,
 517: 0,
 518: 0,
 519: 0,
 520: 0,
 521: 0,
 522: 0,
 523: 0,
 524: 0,
 525: 0,
 526: 0,
 527: 0,
 528: 0,
 529: 0,
 530: 0,
 531: 0,
 532: 0,
 533: 0,
 534: 0,
 535: 0,
 536: 0,
 537: 0,
 538: 0,
 539: 0,
 540: 0,
 541: 0,
 542: 0,
 543: 0,
 544: 0,
 545: 0,
 546: 0,
 547: 0,
 548: 0,
 549: 0,
 550: 0,
 551: 0,
 552: 0,
 553: 0,
 554: 0,
 555: 0,
 556: 0,
 557: 0,
 558: 0,
 559: 0,
 560: 0,
 561: 0,
 562: 0,
 563: 0,
 564: 0,
 565: 0,
 566: 0,
 567: 0,
 568: 0,
 569: 0,
 570: 0,
 571: 0,
 572: 0,
 573: 0,
 574: 0,
 575: 0,
 576: 0,
 577: 0,
 578: 0,
 579: 0,
 580: 0,
 581: 0,
 582: 0,
 583: 0,
 584: 0,
 585: 0,
 586: 0,
 587: 0,
 588: 0,
 589: 0,
 590: 0,
 591: 0,
 592: 0,
 593: 0,
 594: 0,
 595: 0,
 596: 0,
 597: 0,
 598: 0,
 599: 0,
 600: 0,
 601: 0,
 602: 0,
 603: 0,
 604: 0,
 605: 0,
 606: 0,
 607: 0,
 608: 0,
 609: 0,
 610: 0}

In [ ]:
top_match = sorted([(value,key) for (key,value) in user_similarities.items()], reverse=True)
top_n = 10
top_match[:10]

[(0, 610),
 (0, 609),
 (0, 608),
 (0, 607),
 (0, 606),
 (0, 605),
 (0, 604),
 (0, 603),
 (0, 602),
 (0, 601)]

Making the recommendation

In [ ]:
user_df

,1,3,6,47,50,70,101,110,151,157,...,147662,148166,149011,152372,158721,160341,160527,160836,163937,163981
611,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
movies_not_rated = user_df.loc[target_user][movie_df.loc[target_user]==0].index
movies_not_rated

Index([     1,      3,      6,     47,     50,     70,    101,    110,    151,
          157,
       ...
       147662, 148166, 149011, 152372, 158721, 160341, 160527, 160836, 163937,
       163981],
      dtype='int64', length=9713)

In [ ]:
recommendations = []

for u in top_match[:5]:
  u_ratings = movie_df.loc[u[1]]
  for i in u_ratings.index:
    if u_ratings.loc[i]!=0 and i in movies_not_rated:
      recommendations.append( (u_ratings.loc[i], str(movie_names.loc[movie_names["movieId"]==i, "title"])) )

In [ ]:
sorted(recommendations, reverse=True)[:20]

[]